USE [master]
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'filmDB')
BEGIN
  ALTER DATABASE [filmDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE [filmDB];
END;
GO

/****** Object:  Database [filmDB]    Script Date: 29-04-2024 08:13:24 ******/
CREATE DATABASE [filmDB]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'filmDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DBFELIX\MSSQL\DATA\filmDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'filmDB2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DBFELIX\MSSQL\DATA\filmDB2.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'filmDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DBFELIX\MSSQL\DATA\filmDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [filmDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [filmDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [filmDB] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [filmDB] SET ANSI_NULLS OFF
GO
ALTER DATABASE [filmDB] SET ANSI_PADDING OFF
GO
ALTER DATABASE [filmDB] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [filmDB] SET ARITHABORT OFF
GO
ALTER DATABASE [filmDB] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [filmDB] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [filmDB] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [filmDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [filmDB] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [filmDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [filmDB] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [filmDB] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [filmDB] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [filmDB] SET  DISABLE_BROKER
GO
ALTER DATABASE [filmDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [filmDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [filmDB] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [filmDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [filmDB] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [filmDB] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [filmDB] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [filmDB] SET RECOVERY FULL
GO
ALTER DATABASE [filmDB] SET  MULTI_USER
GO
ALTER DATABASE [filmDB] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [filmDB] SET DB_CHAINING OFF
GO
ALTER DATABASE [filmDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [filmDB] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [filmDB] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [filmDB] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'filmDB', N'ON'
GO
ALTER DATABASE [filmDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [filmDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
ALTER DATABASE [filmDB] SET  READ_WRITE
GO

CREATE TABLE Film (
  ID INT PRIMARY KEY,
  Titel nvarchar(255) NOT NULL,
  Instruktør nvarchar(255),
  Spilletid INT CHECK (Spilletid BETWEEN 0 AND 180), -- Enforce spilletid range
  Beskrivelse ntext,
  GenreNavn nvarchar(255) FOREIGN KEY REFERENCES Genre(GenreNavn)
);
GO

CREATE TABLE Genre (
  GenreNavn nvarchar(255) PRIMARY KEY
);
GO

CREATE TABLE Skuespiller (
  ID INT PRIMARY KEY,
  Navn nvarchar(255) NOT NULL,
  Portræt BLOB  -- Portræt can be an image
);
GO

CREATE TABLE FilmSkuespiller (
  FilmID INT FOREIGN KEY REFERENCES Film(ID),
  SkuespillerID INT FOREIGN KEY REFERENCES Skuespiller(ID),
  PRIMARY KEY (FilmID, SkuespillerID)
);
GO
